# use an official Ubuntu image as base image
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y build-essential iputils-ping

COPY node_app.cpp hvac_server.cpp /app/

WORKDIR /app

RUN g++ node_app.cpp -o node_app
RUN g++ hvac_server.cpp -o hvac_server

ENV NODE_NAME default_node

CMD ["./hvac_server"]


# # Use an official Ubuntu base image
# FROM ubuntu:20.04

# # Set noninteractive mode for apt-get
# ENV DEBIAN_FRONTEND=noninteractive

# # Update package list and install necessary packages
# RUN apt-get update && apt-get install -y \
#     build-essential \
#     cmake \
#     git \
#     libssl-dev \
#     python3 \
#     python3-pip \
#     && rm -rf /var/lib/apt/lists/*

# # Set the working directory inside the container
# WORKDIR /app

# # Copy your project files into the container (if applicable)
# # COPY . /app

# # (Optional) Build your application here if you have a Makefile or CMakeLists.txt
# # RUN cmake . && make

# # Expose a port if your application requires it (optional)
# # EXPOSE 8080

# # Define the default command for the container
# CMD ["bash"]
